sudo: required

dist: xenial

os:
  - linux

language: python

before_install:
  # configure a headless display
  - source ./travis/setup_headless_display.sh
  
  
install:
  - "pip install -q pyglet"

script:
  - python -c "import pyglet; r = pyglet.gl.gl_info.get_renderer(); print(r); assert 'gallium' in r.lower()"
  
  
notifications:
  email: false
