sudo: required

dist: xenial

os:
  - linux

language: python

before_install:
  # configure a headless display
  - source ./travis/setup_headless_display.sh
  
  
install:
  - "pip install pyvista"

script:
  - python -c "from pyvista import examples; examples.load_globe().plot();"
  
  
notifications:
  email: false
